/// Small shared UI pieces: error states, provider badges, stat chips and the
/// themed generation loader.
library;

import 'package:flutter/material.dart';

import '../models/provider.dart';
import '../services/api_exception.dart';
import '../theme/palette.dart';

// ---------------------------------------------------------------- error card

/// A real error state: what happened, whether retrying is worth it, and a
/// concrete next step. Never a bare "something went wrong".
class ApiErrorCard extends StatelessWidget {
  const ApiErrorCard({required this.error, required this.onRetry, this.retryLabel = 'Try again', super.key});

  final ApiException error;
  final VoidCallback? onRetry;
  final String retryLabel;

  @override
  Widget build(BuildContext context) {
    final colors = context.gameColors;
    final (icon, title) = switch (error) {
      ApiUnreachableException() => (Icons.wifi_off_rounded, 'Cannot reach the API'),
      ApiTimeoutException() => (Icons.hourglass_disabled_rounded, 'The API timed out'),
      MalformedResponse() => (Icons.broken_image_rounded, 'Unexpected response'),
      ApiServerException(isUnknownGame: true) => (Icons.search_off_rounded, 'That game is gone'),
      ApiServerException(isUnknownProblem: true) => (Icons.search_off_rounded, 'Unknown problem'),
      ApiServerException(isGenerationFailure: true) => (Icons.block_rounded, 'Generation failed'),
      ApiServerException() => (Icons.report_gmailerrorred_rounded, 'The API returned an error'),
    };
    final detail = switch (error) {
      ApiUnreachableException(:final baseUrl) => 'Start the server, or point the app at your machine with\n'
          '--dart-define=API_BASE_URL=http://<your-lan-ip>:8787\n(currently $baseUrl)',
      ApiServerException(:final code, :final statusCode) => '$code · HTTP $statusCode',
      _ => null,
    };

    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: Color.lerp(colors.surface, colors.danger, 0.10)!,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: colors.danger.withValues(alpha: 0.5)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Icon(icon, size: 18, color: colors.danger),
              const SizedBox(width: 8),
              Expanded(
                child: Text(
                  title,
                  style: TextStyle(fontSize: 14, fontWeight: FontWeight.w800, color: colors.onSurface),
                ),
              ),
            ],
          ),
          const SizedBox(height: 7),
          Text(
            error.message,
            style: TextStyle(fontSize: 12, height: 1.35, color: colors.muted),
          ),
          if (detail != null) ...[
            const SizedBox(height: 6),
            Text(
              detail,
              style: TextStyle(
                fontSize: 11,
                height: 1.35,
                color: colors.muted.withValues(alpha: 0.75),
                fontFamily: 'monospace',
              ),
            ),
          ],
          if (onRetry != null) ...[
            const SizedBox(height: 12),
            FilledButton.icon(
              onPressed: onRetry,
              icon: const Icon(Icons.refresh_rounded, size: 17),
              label: Text(retryLabel),
              style: FilledButton.styleFrom(backgroundColor: colors.danger),
            ),
          ],
        ],
      ),
    );
  }
}

// ------------------------------------------------------------ provider badge

/// Makes the generating provider visible, which is the point of `usedTier` +
/// `attempts` in the contract: the player can see whether an LLM or the
/// template tier built the game they are playing.
class ProviderBadge extends StatelessWidget {
  const ProviderBadge({required this.tier, this.attempts = const [], this.dense = false, super.key});

  final ProviderTier? tier;
  final List<ProviderAttempt> attempts;
  final bool dense;

  @override
  Widget build(BuildContext context) {
    final colors = context.gameColors;
    final resolved = tier;
    if (resolved == null) return const SizedBox.shrink();
    final color = resolved.isGenerated ? colors.primary : colors.muted;
    final failed = attempts.where((a) => !a.ok).toList(growable: false);

    return Tooltip(
      message: failed.isEmpty
          ? 'Generated by the ${resolved.label} tier'
          : 'Generated by ${resolved.label} after '
              '${failed.map((a) => a.tier.label).join(', ')} failed',
      child: Container(
        padding: EdgeInsets.symmetric(horizontal: dense ? 6 : 8, vertical: dense ? 2 : 3),
        decoration: BoxDecoration(
          color: color.withValues(alpha: 0.14),
          borderRadius: BorderRadius.circular(7),
          border: Border.all(color: color.withValues(alpha: 0.4)),
        ),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(
              resolved.isGenerated ? Icons.auto_awesome_rounded : Icons.dashboard_customize_rounded,
              size: dense ? 10 : 12,
              color: color,
            ),
            const SizedBox(width: 4),
            // The badge can land in a tight constraint (a header row next to a
            // title), so its text shrinks instead of overflowing.
            Flexible(
              child: Text(
                resolved.label,
                maxLines: 1,
                overflow: TextOverflow.ellipsis,
                style: TextStyle(
                  fontSize: dense ? 9.5 : 10.5,
                  fontWeight: FontWeight.w800,
                  color: color,
                ),
              ),
            ),
            if (failed.isNotEmpty) ...[
              const SizedBox(width: 4),
              Flexible(
                child: Text(
                  '(${attempts.length} tried)',
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                  style: TextStyle(fontSize: 9, color: colors.muted),
                ),
              ),
            ],
          ],
        ),
      ),
    );
  }
}

// --------------------------------------------------------------- stat chips

class StatChip extends StatelessWidget {
  const StatChip({required this.label, required this.value, this.color, this.icon, super.key});

  final String label;
  final String value;
  final Color? color;
  final IconData? icon;

  @override
  Widget build(BuildContext context) {
    final colors = context.gameColors;
    final tint = color ?? colors.muted;
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 9, vertical: 5),
      decoration: BoxDecoration(
        color: Color.lerp(colors.surface, tint, 0.13),
        borderRadius: BorderRadius.circular(9),
        border: Border.all(color: tint.withValues(alpha: 0.35)),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          if (icon != null) ...[
            Icon(icon, size: 11, color: tint),
            const SizedBox(width: 4),
          ],
          Text(
            label,
            style: TextStyle(fontSize: 10, fontWeight: FontWeight.w700, color: tint),
          ),
          const SizedBox(width: 4),
          Text(
            value,
            style: TextStyle(fontSize: 11.5, fontWeight: FontWeight.w900, color: colors.onSurface),
          ),
        ],
      ),
    );
  }
}

/// `O(log n)` style complexity chips.
class ComplexityChips extends StatelessWidget {
  const ComplexityChips({required this.chips, this.dense = false, super.key});

  final List<(String, String)> chips;
  final bool dense;

  @override
  Widget build(BuildContext context) {
    final colors = context.gameColors;
    if (chips.isEmpty) return const SizedBox.shrink();
    return Wrap(
      spacing: 6,
      runSpacing: 6,
      children: [
        for (final (label, value) in chips)
          Container(
            padding: EdgeInsets.symmetric(horizontal: dense ? 7 : 9, vertical: dense ? 3 : 5),
            decoration: BoxDecoration(
              color: Color.lerp(colors.surface, colors.primary, 0.12),
              borderRadius: BorderRadius.circular(8),
              border: Border.all(color: colors.primary.withValues(alpha: 0.3)),
            ),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                Text(
                  label,
                  style: TextStyle(
                    fontSize: 9.5,
                    fontWeight: FontWeight.w700,
                    color: colors.primary,
                  ),
                ),
                const SizedBox(width: 4),
                Text(
                  value,
                  style: TextStyle(
                    fontSize: dense ? 10.5 : 11.5,
                    fontWeight: FontWeight.w900,
                    color: colors.onSurface,
                  ),
                ),
              ],
            ),
          ),
      ],
    );
  }
}

// ---------------------------------------------------------- section heading

class SectionHeading extends StatelessWidget {
  const SectionHeading({required this.title, this.trailing, this.icon, super.key});

  final String title;
  final Widget? trailing;
  final IconData? icon;

  @override
  Widget build(BuildContext context) {
    final colors = context.gameColors;
    return Row(
      children: [
        if (icon != null) ...[
          Icon(icon, size: 12, color: colors.muted),
          const SizedBox(width: 5),
        ],
        Text(
          title.toUpperCase(),
          style: TextStyle(
            fontSize: 9,
            fontWeight: FontWeight.w900,
            letterSpacing: 1.3,
            color: colors.muted,
          ),
        ),
        const Spacer(),
        ?trailing,
      ],
    );
  }
}

// ------------------------------------------------------------- misc helpers

/// A small pill used for mechanics, labels and legend entries.
class MiniLabel extends StatelessWidget {
  const MiniLabel({required this.text, this.color, this.icon, super.key});

  final String text;
  final Color? color;
  final IconData? icon;

  @override
  Widget build(BuildContext context) {
    final colors = context.gameColors;
    final tint = color ?? colors.muted;
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 7, vertical: 3),
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(7),
        border: Border.all(color: tint.withValues(alpha: 0.35)),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          if (icon != null) ...[
            Icon(icon, size: 10, color: tint),
            const SizedBox(width: 3),
          ],
          Text(
            text,
            style: TextStyle(fontSize: 10, fontWeight: FontWeight.w700, color: tint),
          ),
        ],
      ),
    );
  }
}

/// A consistent "no data" row, so empty states never look like bugs.
class EmptyHint extends StatelessWidget {
  const EmptyHint({required this.text, this.icon = Icons.hourglass_empty_rounded, super.key});

  final String text;
  final IconData icon;

  @override
  Widget build(BuildContext context) {
    final colors = context.gameColors;
    return Row(
      children: [
        Icon(icon, size: 13, color: colors.muted.withValues(alpha: 0.6)),
        const SizedBox(width: 7),
        Expanded(
          child: Text(
            text,
            style: TextStyle(fontSize: 11.5, color: colors.muted.withValues(alpha: 0.8)),
          ),
        ),
      ],
    );
  }
}
