'use client'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { getProblem, DSA_TOPICS } from '@dsa/game-schema'
import { useAuth } from '@/components/auth/AuthProvider'
import { learningRequest, chatLink, type LearningDashboard } from '@/lib/learning-api'
import { Markdown } from './Markdown'
type Record = LearningDashboard['records'][number]
export function DashboardView() {
 const {user}=useAuth()
 const [data,setData]=useState<LearningDashboard|null>(null),[error,setError]=useState(''),[reload,setReload]=useState(0)
 const [plans,setPlans]=useState<{id:string;title:string;content:string}[]>([]),[planError,setPlanError]=useState(''),[plansLoading,setPlansLoading]=useState(true),[planReload,setPlanReload]=useState(0)
 const [topic,setTopic]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[records,setRecords]=useState<Record[]>([]),[cursor,setCursor]=useState<string|null>(null),[historyError,setHistoryError]=useState(''),[historyLoading,setHistoryLoading]=useState(false)
 useEffect(()=>{let alive=true;setData(null);setError('');learningRequest<LearningDashboard>('/dashboard').then(d=>{if(alive)setData(d)}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[user?.id,reload])
 useEffect(()=>{let alive=true;setPlans([]);setPlansLoading(true);setPlanError('');learningRequest<{plans:typeof plans}>('/plans').then(d=>{if(alive)setPlans(d.plans)}).catch(e=>{if(alive)setPlanError(e.message)}).finally(()=>{if(alive)setPlansLoading(false)});return()=>{alive=false}},[user?.id,planReload])
 const historyPath=(next?:string)=>`/history?${new URLSearchParams({topic,...(from?{from:String(new Date(from+'T00:00:00').getTime())}:{}),...(to?{to:String(new Date(to+'T23:59:59').getTime())}:{}),...(next?{cursor:next}:{})})}`
 useEffect(()=>{let alive=true;setRecords([]);setCursor(null);setHistoryError('');setHistoryLoading(true);learningRequest<{records:Record[];nextCursor:string|null}>(historyPath()).then(d=>{if(alive){setRecords(d.records);setCursor(d.nextCursor)}}).catch(e=>{if(alive)setHistoryError(e.message)}).finally(()=>{if(alive)setHistoryLoading(false)});return()=>{alive=false}},[user?.id,topic,from,to,reload])
 const more=async()=>{if(!cursor)return;setHistoryLoading(true);try{const d=await learningRequest<{records:Record[];nextCursor:string|null}>(historyPath(cursor));setRecords(r=>[...r,...d.records]);setCursor(d.nextCursor)}catch(e){setHistoryError((e as Error).message)}finally{setHistoryLoading(false)}}
 const recent=data?.records.slice(0,10)??[]
 return <main className="mx-auto max-w-6xl space-y-5 px-4 py-8"><header><p className="eyebrow">YOUR LEARNING JOURNEY</p><h1 className="text-3xl font-bold">Your progress</h1><p className="mt-2">Use your recent practice to choose the next useful step.</p></header>{error&&<div role="alert" className="panel p-4">{error}<button className="btn" onClick={()=>setReload(n=>n+1)}>Retry</button></div>}{!data&&!error&&<p role="status">Loading practice history…</p>}{data&&<>
 <section className="panel p-5 flex flex-wrap justify-between gap-4"><div><h2 className="text-xl font-bold">Your next step</h2><p>{data.recommendation?.reason??'Pick a mission to begin.'}</p>{data.recommendation&&<Link className="btn btn-primary mt-3" href={data.recommendation.gameId?`/play/${data.recommendation.gameId}`:`/problem/${data.recommendation.problemId}`}>{data.recommendation.gameId?'Resume: ':''}{getProblem(data.recommendation.problemId)?.title} →</Link>}</div><Link className="btn self-start" href={chatLink('Review my practice history. What have I struggled with and what should I study next?')}>Discuss my progress</Link></section>
 <section className="panel p-5"><h2 className="text-xl font-bold">Recent performance</h2><p>Last {recent.length} recorded runs: {recent.reduce((n,r)=>n+r.mistakes,0)} mistakes · {recent.reduce((n,r)=>n+r.hints,0)} hints</p><p className="text-sm">Completion is a milestone; repeated independent practice gives stronger evidence.</p></section>
 <section><h2 className="text-xl font-bold mb-3">Topics</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{data.topics.map(t=><article className="panel p-4" key={t.topic}><h3 className="font-bold">{t.topic}</h3><p>{t.completed}/{t.total} completed</p><p className="text-sm">{t.attempts} runs · {t.mistakes} mistakes · {t.hints} hints</p><Link className="btn mt-2" href={chatLink(`Review my ${t.topic} practice and explain what to revisit.`)}>Discuss topic</Link></article>)}</div></section>
 <section className="panel p-5"><h2 className="text-xl font-bold">Practice schedule</h2><p className="text-sm">Reviews at 1, 3, 7, and 14 days.</p>{!data.reviews.length?<p>Finish a recorded run to start your review schedule.</p>:<ul>{data.reviews.map(r=><li key={r.problemId} className="flex flex-wrap justify-between gap-3 py-2"><span>{getProblem(r.problemId)?.title} · {r.dueAt<=Date.now()?'Due now':`Due ${new Date(r.dueAt).toLocaleDateString()}`}</span><Link className="btn" href={`/problem/${r.problemId}`}>Review</Link></li>)}</ul>}</section>
 </>}
 <section className="panel p-5"><h2 className="text-xl font-bold">Practice history</h2><div className="flex flex-wrap gap-3 my-3"><label>Topic<select className="input" value={topic} onChange={e=>setTopic(e.target.value)}><option value="">All topics</option>{DSA_TOPICS.map(t=><option key={t}>{t}</option>)}</select></label><label>From<input type="date" className="input" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Through<input type="date" className="input" value={to} onChange={e=>setTo(e.target.value)}/></label></div>{historyError&&<p role="alert">{historyError}<button className="btn" onClick={()=>setReload(n=>n+1)}>Retry history</button></p>}{!records.length&&!historyLoading&&<p>No runs match these filters. Play a signed-in mission to record your practice.</p>}<ul className="divide-y divide-[var(--dsa-border)]">{records.map(r=><li key={r.gameId} className="py-3 flex flex-wrap justify-between gap-3"><div><strong>{getProblem(r.problemId)?.title}</strong><p className="text-sm">{r.difficulty==='easy'?'Low':r.difficulty==='hard'?'High':'Medium'} · {r.steps} steps · {r.mistakes} mistakes · {r.hints} hints · {new Date(r.startedAt).toLocaleDateString()}</p></div><div className="flex gap-2"><Link className="btn" href={r.outcome==='playing'?`/play/${r.gameId}`:`/debrief/${r.gameId}`}>{r.outcome==='playing'?'Resume':'View debrief'}</Link><Link className="btn" href={chatLink('Discuss this practice run. What should I improve?',{type:'run',gameId:r.gameId})}>Discuss</Link></div></li>)}</ul>{historyLoading&&<p role="status">Loading history…</p>}{cursor&&<button className="btn" disabled={historyLoading} onClick={()=>void more()}>Load more runs</button>}</section>
 {data&&<details className="adventure-drawer"><summary>Completion stamps · {Object.keys(data.completed).length}</summary><ul className="p-4">{Object.entries(data.completed).map(([id,date])=><li key={id}>{getProblem(id)?.title??id} · {new Date(date).toLocaleDateString()}{!data.records.some(r=>r.problemId===id&&r.completedAt)&&' · completion only; performance unavailable'}</li>)}</ul></details>}
 <section><h2 className="text-xl font-bold mb-3">Saved study plans</h2>{plansLoading&&<p role="status">Loading plans…</p>}{planError&&<p role="alert">{planError}<button className="btn" onClick={()=>setPlanReload(n=>n+1)}>Retry plans</button></p>}{!plansLoading&&!planError&&!plans.length&&<p>Create a study plan in Chat and save it here.</p>}{plans.map(p=><details key={p.id} className="adventure-drawer"><summary>{p.title}</summary><div className="p-4"><Markdown text={p.content}/></div></details>)}</section></main>
}
