import type { DsaTopic } from './problems.js'
export interface TopicLesson { topic: DsaTopic; title: string; concept: string; example: string; code: string }
/** Reviewed foundations; these snippets illustrate a technique rather than solve every mapped task. */
export const TOPIC_LESSONS: TopicLesson[] = [
 {topic:'arrays',title:'Arrays and running state',concept:'An array stores ordered values. Many linear scans keep a small running state instead of re-reading earlier values.',example:'For [3,1,7], the running maximum is 3, then 3, then 7.',code:'def maximum(values):\n    if not values:\n        return None\n    best = values[0]\n    for value in values[1:]:\n        best = max(best, value)\n    return best'},
 {topic:'sorting',title:'Sorting by an invariant',concept:'A sorting algorithm progressively establishes order. In insertion sort, the prefix before the current item is already sorted.',example:'Insert 2 into the sorted prefix [1,4]: shift 4 right to obtain [1,2,4].',code:'def insertion_sort(a):\n    for i in range(1, len(a)):\n        value, j = a[i], i - 1\n        while j >= 0 and a[j] > value:\n            a[j + 1] = a[j]\n            j -= 1\n        a[j + 1] = value\n    return a'},
 {topic:'stack',title:'Stacks: last in, first out',concept:'A stack remembers nested work. The most recent unfinished item is handled first.',example:'For (), push the opening bracket, then pop it when the closing bracket arrives.',code:'def balanced(text):\n    stack = []\n    pairs = {"(": ")", "[": "]", "{": "}"}\n    for char in text:\n        if char in pairs:\n            stack.append(pairs[char])\n        elif not stack or stack.pop() != char:\n            return False\n    return not stack'},
 {topic:'queue',title:'Queues: first in, first out',concept:'A queue processes items in arrival order. Breadth-first traversal uses it to explore each level before the next.',example:'Enqueue A, then B. Dequeue returns A before B.',code:'from collections import deque\nqueue = deque(["A", "B"])\nfirst = queue.popleft()\nqueue.append("C")'},
 {topic:'binary-search',title:'Binary search on sorted data',concept:'Keep a range containing every possible answer. Each comparison removes a half that cannot contain the target.',example:'Search 7 in [1,3,7,9]: compare 3, then search indices 2 through 3.',code:'def search(a, target):\n    lo, hi = 0, len(a) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if a[mid] == target:\n            return mid\n        if a[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid - 1\n    return -1'},
 {topic:'linked-list',title:'Follow links, preserve reachability',concept:'A linked list is a sequence of nodes connected by next pointers. Save the next node before changing a link.',example:'To reverse A → B → null, keep B reachable before changing A.next to null.',code:'def reverse(head):\n    previous = None\n    while head is not None:\n        following = head.next\n        head.next = previous\n        previous, head = head, following\n    return previous'},
 {topic:'hash-table',title:'Hash tables and frequencies',concept:'A hash table maps keys to values. Frequency counts make repeated membership and counting queries efficient on average.',example:'Counting [a,b,a] gives {a:2,b:1}.',code:'def frequencies(values):\n    counts = {}\n    for value in values:\n        counts[value] = counts.get(value, 0) + 1\n    return counts'},
 {topic:'strings',title:'Strings and two pointers',concept:'Strings are ordered character sequences. Two pointers can compare mirrored positions without creating a reversed copy.',example:'For radar, compare r with r, then a with a; the middle needs no pair.',code:'def palindrome(s):\n    left, right = 0, len(s) - 1\n    while left < right:\n        if s[left] != s[right]:\n            return False\n        left += 1\n        right -= 1\n    return True'},
 {topic:'trees',title:'Trees and recursive subproblems',concept:'A binary tree node has up to two children. Traversal order determines when the node is processed relative to its subtrees.',example:'Inorder visits left subtree, root, then right subtree. A valid BST produces sorted values.',code:'def inorder(node):\n    if node is None:\n        return []\n    return inorder(node.left) + [node.value] + inorder(node.right)'},
 {topic:'heap',title:'Heaps and the smallest candidate',concept:'A min-heap exposes its smallest element. Keeping only k candidates makes kth-largest selection efficient.',example:'For k=2 and [3,1,7], retain [3,7]; its minimum 3 is the second-largest value.',code:'import heapq\ndef kth_largest(values, k):\n    if not 1 <= k <= len(values):\n        raise ValueError("Invalid k")\n    heap = []\n    for value in values:\n        heapq.heappush(heap, value)\n        if len(heap) > k:\n            heapq.heappop(heap)\n    return heap[0]'},
 {topic:'graphs',title:'Graphs and visited sets',concept:'A graph connects vertices through edges. A visited set prevents cycles from causing repeated exploration.',example:'In A ↔ B ↔ C, marking A before exploring B prevents returning to A forever.',code:'def reachable(graph, start):\n    seen, pending = set(), [start]\n    while pending:\n        node = pending.pop()\n        if node in seen:\n            continue\n        seen.add(node)\n        pending.extend(graph.get(node, []))\n    return seen'},
 {topic:'dp',title:'Dynamic programming',concept:'When subproblems repeat, store their answers. Define what each state means and how smaller states combine.',example:'With 1- or 2-step climbs, ways(n) = ways(n-1) + ways(n-2). There are 3 ways to climb 3 steps.',code:'def ways(n):\n    if n < 0:\n        return 0\n    previous, current = 1, 1\n    for _ in range(n):\n        previous, current = current, previous + current\n    return previous'},
 {topic:'backtracking',title:'Choose, explore, undo',concept:'Backtracking explores a decision tree. Undo a choice before exploring its sibling so branches do not share accidental state.',example:'The subsets of [1,2] are [], [1], [2], and [1,2].',code:'def subsets(values):\n    result = []\n    def visit(i, chosen):\n        if i == len(values):\n            result.append(chosen.copy())\n            return\n        visit(i + 1, chosen)\n        chosen.append(values[i])\n        visit(i + 1, chosen)\n        chosen.pop()\n    visit(0, [])\n    return result'},
 {topic:'greedy',title:'Greedy choices need a reason',concept:'A greedy method keeps the best local choice when it can be shown to preserve a possible global solution.',example:'For jump lengths [2,0,1], index 0 reaches index 2, which is already the destination.',code:'def can_reach_end(jumps):\n    farthest = 0\n    for i, jump in enumerate(jumps):\n        if i > farthest:\n            return False\n        farthest = max(farthest, i + jump)\n    return bool(jumps)'},
 {topic:'bit-manip',title:'Bit operations and XOR',concept:'XOR cancels equal values: x XOR x = 0, and x XOR 0 = x. This helps when every value except one appears twice.',example:'[4,1,4] reduces to 1 because the two 4 values cancel.',code:'def single_number(values):\n    answer = 0\n    for value in values:\n        answer ^= value\n    return answer'},
 {topic:'trie',title:'Tries share prefixes',concept:'A trie follows one edge per character. A terminal marker distinguishes a complete word from an existing prefix.',example:'The words cat and car share the c → a prefix, then branch.',code:'def insert(root, word):\n    node = root\n    for char in word:\n        node = node.setdefault(char, {})\n    node[None] = True\n\ndef contains(root, word):\n    node = root\n    for char in word:\n        if char not in node:\n            return False\n        node = node[char]\n    return None in node'},
]
